services:
  db-dsh:
    container_name: db-dsh
    image: postgres:14.1
    restart: unless-stopped
    environment:
      - POSTGRES_DB=DSH_dsjh
      - POSTGRES_USER=dsjh
      - POSTGRES_PASSWORD=dsjh
    volumes:
      - ./Database/dsh_db:/var/lib/postgresql/data
      - ./Database/init:/docker-entrypoint-initdb.d/:ro
    ports:
      - "5432:5432"
