/**
 * DSH API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AddressDto { 
    street?: string | null;
    zipCode?: string | null;
    city?: string | null;
    longitude?: number | null;
    latitude?: number | null;
}

