/**
 * DSH API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AuthResponseDto { 
    accessToken?: string | null;
    refreshToken?: string | null;
    expiresAt?: string;
}

