/**
 * DSH API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Sex } from './sex';


export interface CreateStudentDto { 
    avatar?: string | null;
    sex?: Sex;
    firstName?: string | null;
    lastName?: string | null;
    birtday?: string | null;
    activeSince?: string | null;
    instrumentIds?: Array<string> | null;
    teacherIds?: Array<string> | null;
    roomIds?: Array<string> | null;
    lessonIds?: Array<string> | null;
    materialIds?: Array<string> | null;
}
export namespace CreateStudentDto {
}


