/**
 * DSH API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Sex } from './sex';
import { TeacherInstrumentDto } from './teacherInstrumentDto';


export interface TeacherDto { 
    id?: string;
    avatar?: string | null;
    sex?: Sex;
    firstName?: string | null;
    lastName?: string | null;
    fullName?: string | null;
    birthday?: string | null;
    activeSince?: string | null;
    active?: boolean;
    instruments?: Array<TeacherInstrumentDto> | null;
}
export namespace TeacherDto {
}


