/**
 * DSH API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Sex } from './sex';


export interface UpdateTeacherDto { 
    id?: string;
    avatar?: string | null;
    sex?: Sex;
    firstName?: string | null;
    lastName?: string | null;
    birthday?: string | null;
    activeSince?: string | null;
    active?: boolean;
    instrumentIds?: Array<string> | null;
    studentIds?: Array<string> | null;
    roomIds?: Array<string> | null;
    lessonIds?: Array<string> | null;
    materialIds?: Array<string> | null;
}
export namespace UpdateTeacherDto {
}


