export * from './instrument.api.generated';
import { InstrumentApi } from './instrument.api.generated';
export * from './lesson.api.generated';
import { LessonApi } from './lesson.api.generated';
export * from './material.api.generated';
import { MaterialApi } from './material.api.generated';
export * from './room.api.generated';
import { RoomApi } from './room.api.generated';
export * from './student.api.generated';
import { StudentApi } from './student.api.generated';
export * from './teacher.api.generated';
import { TeacherApi } from './teacher.api.generated';
export const APIS = [InstrumentApi, LessonApi, MaterialApi, RoomApi, StudentApi, TeacherApi];
