/**
 * DSH API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateAddressDto } from './createAddressDto';


export interface UpdateRoomDto { 
    id?: string;
    name?: string | null;
    description?: string | null;
    address?: CreateAddressDto;
}

