/**
 * DSH API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateMaterialDto { 
    name?: string | null;
    description?: string | null;
    filetype?: string | null;
    filesize?: number | null;
    filesource?: string | null;
    teacherId?: string | null;
    studentId?: string | null;
}

