/**
 * DSH API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateInstrumentDto { 
    id?: string;
    name?: string | null;
    description?: string | null;
    image?: string | null;
    teacherIds?: Array<string> | null;
    studentIds?: Array<string> | null;
    lessonIds?: Array<string> | null;
}

