/**
 * DSH API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LessonState } from './lessonState';


export interface UpdateLessonDto { 
    startTime?: string;
    endTime?: string;
    teacherId?: string;
    studentId?: string;
    roomId?: string;
    instrumentId?: string;
    state?: LessonState;
}
export namespace UpdateLessonDto {
}


